name: Build IPA and APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:  # Allows manual trigger

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Flutter Doctor
      run: flutter doctor -v
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build APK (release)
      run: flutter build apk --release
      
    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-app
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30

  build-ios:
    needs: build-android
    runs-on: macos-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        
    - name: Flutter Doctor
      run: flutter doctor -v
        
    - name: Install dependencies
      run: flutter pub get
      
    - name: Build iOS (no signing for testing)
      run: |
        flutter build ios --release --no-codesign
        
    - name: Create IPA manually
      run: |
        mkdir -p build/ios/ipa
        cp -r build/ios/iphoneos/Runner.app build/ios/ipa/
        cd build/ios/ipa
        zip -r ../Runner.ipa Runner.app
        
    - name: Upload IPA as artifact
      uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: build/ios/Runner.ipa
        retention-days: 30
